name: CI

on:
  push:
    branches:
      - main
      - "v*.*.*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.1"
          elixir-version: "1.14.2"
          gleam-version: nightly

      - name: Check formatting
        run: mix format --check-formatted

      - name: Install archive
        run: mix do archive.build, archive.install --force
        env:
          MIX_ENV: prod

      - name: Get basic project deps
        run: mix deps.get
        working-directory: test_projects/basic_project

      - name: Test basic project
        run: mix test
        working-directory: test_projects/basic_project

      - name: Gleam test basic project
        run: mix gleam.test
        working-directory: test_projects/basic_project
